start_url: "http://www.gmpeye.co.kr/gmpguidesandguidelines/gmpguides.htm"
allowed_netloc: "www.gmpeye.co.kr"
max_depth: 4
max_pages: 500
timeout: 20
rate_sleep_sec: 0.2
out_dir: "data/raw"
meta_dir: "data/meta"
prepared_dir: "data/prepared"
vector_dir: "vectorstore"
user_agent: "Mozilla/5.0 (compatible; gmpeye-pdf-crawler/1.0)"
